### ISSUE TITLE
Options Usage should be better described

### ISSUE THREAD

**Issue by kuczek** [AndrewKeig/grunt-jscoverage#4]

**Comment by m1kc** [comment]
`options` array is passed directly to `jscoverage.processFile()`. Unfortunately, jscoverage doesn't provide any documentation about its programmatic API, so we don't, too.

Actually, `master` version of jscoverage seems to be ignoring passed options at all.

**Comment by m1kc** [comment]
I made a remark about this in Readme: 54e4ac574d86f337dfbda8d983f5e81b27766557. Hope it resolves the issue.
