### ISSUE TITLE
no target found for jscoverage for grunt

### ISSUE THREAD

**Issue by shabfactor** [AndrewKeig/grunt-jscoverage#6]
```
               Tests completed in 3251 milliseconds
               Tests completed in 3251 milliseconds
               259 tests of 259 passed, 0 failed.
               259 tests of 259 passed, 0 failed.
              OK
              >> 259 assertions passed (3251ms)
              >> No "jscoverage" targets found.
               Warning: Task "jscoverage" failed. Use --force to continue.

        Aborted due to warnings.
```

 i setup the jscoverage as given in this code but still getting this error. please help

my code is below  :

```
    jscoverage : {
       src: {
      expand: true,
      cwd: 'src/',
      src: ['**/*.js'],
      ext: '.js'
    },
    otherstuff: {
      expand: true,
      cwd: 'otherstuff/',
      src: ['**/*.js'],
      dest: 'otherstuff-cov/',
      ext: '.js'
    },
    options: {
    }
  },
```

**Comment by m1kc** [comment]
Looks like you forgot to call `loadNpmTasks()`. Add this line to your Gruntfile:

``` js
grunt.loadNpmTasks("grunt-jscoverage");
```

**Comment by shabfactor** [comment]
i did sorry forgot to mention but still the same error

**Comment by m1kc** [comment]
Well, you obviously misconfigured something. Check out [Readme](https://github.com/AndrewKeig/grunt-jscoverage/blob/master/README.md) again. Make sure that grunt-jscoverage is installed, and listed in package.json, and properly loaded during the execution of Gruntfile. Check out Grunt documentation ([getting started](http://gruntjs.com/getting-started), [configuring tasks](http://gruntjs.com/configuring-tasks), [sample Gruntfile](http://gruntjs.com/sample-gruntfile)) for better understanding how Grunt works and how to use it. If you need a living example, see [this Gruntfile](https://github.com/uonline/uonline/blob/master/Gruntfile.coffee#L135-L141) (it's in CoffeeScript, but I believe that won't be a problem). Let me know if you'll have any problems.
